### ISSUE TITLE
Error using fhmm_relaxed

### ISSUE THREAD

**Issue by qingshuimonk** [MingjunZhong/LatentBayesianMelding#1]
I got an error message when running fhmm_relaxed, it said:
`Traceback (most recent call last):
  File "runLBM.py", line 5, in <module>
    from LatentBayesianMelding import fhmm_relaxed
  File "/usr/local/lib/python2.7/dist-packages/LatentBayesianMelding/fhmm_relaxed.py", line 12, in <module>
    import mosek.fusion
  File "/home/lab/.local/lib/python2.7/site-packages/mosek/__init__.py", line 323, in <module>
    raise ImportError('Failed to import dll "%s"' % __libname)
ImportError: Failed to import dll "libmosekxx7_1.so"`
I guess I've not installed mosek correctly. What I did was:
1. As it is recommended in mosek's repo, I used "pip install --user https://github.com/MOSEK/Mosek.pip/archive/7.1.45.tar.gz"
2. I put the license file in /home/usr/mosek folder

**Comment by MingjunZhong** [comment]
@qingshuimonk I am not quite sure the problem, but it looks it is a similar problem with [this](https://groups.google.com/forum/#!topic/mosek/vhPRUnPR7vA).
If you use 32-bit Python, then you should use 32-bit MOSEK.

Make sure to store the license file in the right directory [here](https://mosek.com/resources/downloads/faq/howto-install-license)

**Comment by qingshuimonk** [comment]
I've tried to set PYTHONPATH as a space as suggested in [here](https://groups.google.com/forum/#!topic/mosek/vhPRUnPR7vA). I've checked that I'm using 64bit python now. I download MOSEK from their website and installed it followed by [this document](http://docs.mosek.com/8.0/pythonfusion.pdf). All did not work.

Then I started thinking maybe I should do 

> pip install --user git+http://github.com/MOSEK/Mosek.pip

As suggested in their [repo](https://github.com/MOSEK/Mosek.pip). But I got an error message said:

> Collecting git+http://github.com/MOSEK/Mosek.pip
>   Cloning http://github.com/MOSEK/Mosek.pip to /tmp/pip-Atmcen-build
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-Atmcen-build/setup.py", line 37, in <module>
>         raise VersionError('No version entry in PKG-INFO')
>     **main**.VersionError: No version entry in PKG-INFO
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Atmcen-build/

Anyway, whatever the reason is, I guess this is not a problem in your repo. I appreciate your help and you can close it if you want.
I'll continue to play with it for some time : )

**Comment by MingjunZhong** [comment]
Instead of using pip, why not to download the package and then install it like [here](http://docs.mosek.com/7.0/toolsinstall/Linux_UNIX_installation_instructions.html)?
I am too busy by the end of next week - I will test it after then.

**Comment by MingjunZhong** [comment]
I did have no problems following the steps in [this link](http://docs.mosek.com/7.0/toolsinstall/Linux_UNIX_installation_instructions.html). Just remember to put the license file to the correct directory.

**Comment by MingjunZhong** [comment]
I have updated all the source files, not you do not need the nilmtk. I also include the Mosek installation file, if you follow the instructions, you should be able to install and use it.
