### ISSUE TITLE
Error: The A matrix contains a huge value of -xxxx in constraint '' (518401) at variable '' 

### ISSUE THREAD

**Issue by loneharoon** [MingjunZhong/LatentBayesianMelding#7]
On some homes, I get the following error message

```
*************Iteration: 1*****************
Employing the Mosek solver to solve the problem:

Declaring variables and constraints...


 Solving the problem ...

+++++++++++++++optimization status+++++++++++++++++++
Number of variables:4752080
Number of constraints:3369624
Primal solution status:SolutionStatus.NearOptimal
Primal value:7102822481.03
Dual solution status:SolutionStatus.NearOptimal
Dual value:7102810893.03
Accepted solution status:AccSolutionStatus.Anything
+++++++++++++++optimization status+++++++++++++++++++
Solving this problem took '1027.571136' seconds

 log(datalikelihood*prior)=2445122.95885

*************Iteration: 2*****************
Employing the Mosek solver to solve the problem:

Declaring variables and constraints...


 Solving the problem ...

+++++++++++++++optimization status+++++++++++++++++++
Number of variables:4752080
Number of constraints:3369624
Primal solution status:SolutionStatus.Unknown
Primal value:17267699554.3
Dual solution status:SolutionStatus.Unknown
Dual value:-1.29430552726e+11
Accepted solution status:AccSolutionStatus.Anything
+++++++++++++++optimization status+++++++++++++++++++
Solving this problem took '948.539571047' seconds

 log(datalikelihood*prior)=365592.635728

*************Iteration: 3*****************
Employing the Mosek solver to solve the problem:

Declaring variables and constraints...


 Solving the problem ...

+++++++++++++++optimization status+++++++++++++++++++
Number of variables:4752080
Number of constraints:3369624
Primal solution status:SolutionStatus.Unknown
Primal value:6.46956152104e+13
Dual solution status:SolutionStatus.Unknown
Dual value:-7.62090154457e+12
Accepted solution status:AccSolutionStatus.Anything
+++++++++++++++optimization status+++++++++++++++++++
Solving this problem took '879.327147007' seconds

 log(datalikelihood*prior)=-5628426.5909

*************Iteration: 4*****************
Employing the Mosek solver to solve the problem:

Declaring variables and constraints...

Traceback (most recent call last):

  File "<ipython-input-153-e71c0dc10a48>", line 5, in <module>
    results = lbm.disaggregate_chunk(val)

  File "latent_Bayesian_melding.py", line 245, in disaggregate_chunk
    prediction = self.disaggregate_fixedPrecision(mains_chunk)

  File "latent_Bayesian_melding.py", line 410, in disaggregate_fixedPrecision
    Domain.inRotatedQCone())

  File "/Volumes/MacintoshHD2/Users/haroonr/.local/lib/python2.7/site-packages/mosek/fusion/__init__.py", line 31751, in constraint
    return Model._constraint_Omosek_fusion_Expression_2Omosek_fusion_Domain_2(self,*args)

  File "/Volumes/MacintoshHD2/Users/haroonr/.local/lib/python2.7/site-packages/mosek/fusion/__init__.py", line 30769, in _constraint_Omosek_fusion_Expression_2Omosek_fusion_Domain_2
    return ( self.__constraint_1_SOmosek_fusion_Set_2Omosek_fusion_Expression_2Omosek_fusion_Domain_2(None,None,expr,dom) )

  File "/Volumes/MacintoshHD2/Users/haroonr/.local/lib/python2.7/site-packages/mosek/fusion/__init__.py", line 29177, in __constraint_1_SOmosek_fusion_Set_2Omosek_fusion_Expression_2Omosek_fusion_Domain_2
    ( self._task_1putarowslice_II_3L_3I_3F(first,last,ptrb,varidxs,cof) )

  File "/Volumes/MacintoshHD2/Users/haroonr/.local/lib/python2.7/site-packages/mosek/fusion/__init__.py", line 308, in _task_1putarowslice_II_3L_3I_3F
    self.__task.putarowlist(sub, ptrb[:-1], ptrb[1:], subj, cof);

  File "/Volumes/MacintoshHD2/Users/haroonr/.local/lib/python2.7/site-packages/mosek/__init__.py", line 207, in accept
    return fun(*[ t(a) for (t,a) in zip(argtlst,args) ])

  File "/Volumes/MacintoshHD2/Users/haroonr/.local/lib/python2.7/site-packages/mosek/__init__.py", line 8516, in putarowlist
    raise Error(rescode(res),msg)

Error: The A matrix contains a huge value of -1.2e+22 in constraint '' (518401) at variable '' (604796).
```
This error generated during the 4th iteration. I don't understand how to debug it? Can you please provide few pointers how should I find the error source?

**Comment by MingjunZhong** [comment]
This error came when estimating the noise variances; there might be numerical errors when estimating the noise variances defined in the model.
It seems that this error occurred after the noise variances were estimated in the method `estimate_noisevariance()' in `latent_Bayesian_melding.py'.
